markdown: rdiscount
permalink: /:title/
url: http://leoYY.github.io
name: leoYY
author: yy
qq: 
email: 
duoshuo: 
beian: 
cnzz: 
weibo: 
github: leoYY
pygments: true
safe: true
paginate: 20
about: "这里是 leoYY 的个人博客"
